spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/KuraFlow}
    username: ${DB_USERNAME:KuraFlow}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: user_schema
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: user_schema
    default-schema: user_schema
    create-schemas: true
  mail:
    host: localhost
    port: 1025
    username: test
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  health:
    mail:
      enabled: false

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

vapid:
  public.key: ${VAPID_PUBLIC_KEY}
  private.key: ${VAPID_PRIVATE_KEY}
  subject: ${VAPID_SUBJECT:mailto:admin@kuraflow.com}

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
