spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/KuraFlow
    username: KuraFlow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: user_schema
    default-schema: user_schema
    create-schemas: true

server:
  port: 8082
