spring:
  application:
    name: progress-service
  datasource:
    url: jdbc:postgresql://localhost:5432/KuraFlow
    username: KuraFlow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: progress_schema
    default-schema: progress_schema
    create-schemas: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    properties:
      spring.json.type.mapping: lessonCompleted:com.kuraflow.shared.events.LessonCompletedEvent,reviewCompleted:com.kuraflow.shared.events.ReviewCompletedEvent

server:
  port: 8084

# Kafka Topics
app:
  kafka:
    topics:
      lesson-completed: lesson.completed
      review-completed: review.completed

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
