spring:
  application:
    name: gamification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/KuraFlow}
    username: ${DB_USERNAME:KuraFlow}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: gamification_schema
    default-schema: gamification_schema
    create-schemas: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gamification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.kuraflow.shared.events"
        spring.json.type.mapping: lessonCompleted:com.kuraflow.shared.events.LessonCompletedEvent,reviewCompleted:com.kuraflow.shared.events.ReviewCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8085

# Kafka Topics
app:
  kafka:
    topics:
      lesson-completed: lesson.completed
      review-completed: review.completed
  leaderboard:
    weekly-key: "leaderboard:weekly"
    alltime-key: "leaderboard:alltime"
    page-size: 50
  user-service:
    base-url: "http://localhost:8082"

jwt:
  secret: ${JWT_SECRET}
