spring:
  application:
    name: gamification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/KuraFlow
    username: KuraFlow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: gamification_schema
    default-schema: gamification_schema
    create-schemas: true

server:
  port: 8085
