spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://localhost:5432/KuraFlow
    username: KuraFlow
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    create-schemas: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
